let imya = prompt ("Ваше имя?");
console.log(imya);
let a = prompt("Введите первое число");
let b = prompt("Введите второе число");
let sum = parseInt(a) + parseInt(b);
alert(sum);
let c = prompt("Введите первое число");
let d = prompt("Введите второе число");
let mult = parseInt(c) * parseInt(d);
alert(mult);
